import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:mars_launcher/logic/temperature_manager.dart';
import 'package:mars_launcher/logic/utils.dart';
import 'package:mars_launcher/services/service_locator.dart';
import 'package:mars_launcher/theme/theme_constants.dart';
import 'package:url_launcher/url_launcher.dart';

class OpenWeatherAPIDialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const title = 'Set OpenWeather API key';
    const dialogText = "To provide accurate weather predictions for your location, this app uses the OpenWeather API. "
        "Since the use of the API costs something from 1000 API calls per day and this app is "
        "and should remain free of charge, anyone who is interested can generate and insert their own API key. "
        "A API key can be generated by creating an account on ";

    final textColor = Theme.of(context).scaffoldBackgroundColor;

    return AlertDialog(
      title: const Text(
        title,
        style: TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 18,
        ),
      ),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            RichText(
              textAlign: TextAlign.justify,
              softWrap: true,
              text: TextSpan(
                style: TextStyle(fontSize: 13, color: textColor),
                children: [
                  const TextSpan(text: dialogText),
                  TextSpan(
                    text: "OpenWeatherMap",
                    style: const TextStyle(
                      color: Colors.blue,

                      /// Set the color of the link
                    ),
                    recognizer: TapGestureRecognizer()
                      ..onTap = () {
                        /// Define the URL to open when the link is tapped
                        final uri = Uri.parse("https://openweathermap.org/api");

                        /// Use the url_launcher package to open the URL
                        launchUrl(uri);
                      },
                  ),
                  const TextSpan(text: "."),
                ],
              ),
            ),
            const SizedBox(height: 14),
            const OpenWeatherApiKeyTextField(),
          ],
        ),
      ),
    );
  }
}

class OpenWeatherApiKeyTextField extends StatefulWidget {
  const OpenWeatherApiKeyTextField({Key? key}) : super(key: key);

  @override
  _OpenWeatherApiKeyTextFieldState createState() => _OpenWeatherApiKeyTextFieldState();
}

class _OpenWeatherApiKeyTextFieldState extends State<OpenWeatherApiKeyTextField> {
  TextEditingController _controller = TextEditingController();
  String? _errorText;

  final temperatureManager = getIt<TemperatureManager>();

  @override
  void initState() {
    super.initState();
    if (temperatureManager.apiKey != null && temperatureManager.apiKey!.isNotEmpty) {
      _controller.text = temperatureManager.apiKey!;
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDarkMode = isThemeDark(context);
    final buttonStyle = getDialogButtonStyle(isDarkMode);

    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        TextField(
          // cursorColor: widget.textColor,
          controller: _controller,
          style: TextStyle(color: Theme.of(context).primaryColor),
          decoration: InputDecoration(
            hintText: "Enter API Key",
            errorText: _errorText,
            filled: true,
            fillColor: isDarkMode ? Colors.black87 : Colors.white,
          ),
        ),
        SizedBox(height: 16.0),
        Row(children: [
          TextButton(
            onPressed: () {
              temperatureManager.deleteAPIKey();
              _controller.text = "";
              setErrorText(null);
            },
            child: const Text("DELETE"),
            style: buttonStyle,
          ),
          Expanded(child: SizedBox()),
          TextButton(
            child: const Text('ADD'),
            onPressed: () async {
              var apiKey = _controller.text.trim();
              if (await isInputValid(apiKey)) {
                temperatureManager.addApiKey(apiKey);
                Navigator.of(context).pop();
              }
            },
            style: buttonStyle.copyWith(
              backgroundColor: MaterialStatePropertyAll(Colors.green.withOpacity(0.3)),
              foregroundColor: const MaterialStatePropertyAll(Colors.green),
            ),
          ),
        ]),
      ],
    );
  }

  /// Checks if apiKey is not empty and valid
  Future<bool> isInputValid(apiKey) async {
    if (apiKey.isEmpty) {
      setErrorText('Field cannot be empty');
      return false;
    } else {
      final isValid = await temperatureManager.isApiKeyValid(apiKey);
      if (!isValid) {
        setErrorText('API Key not valid');
        return false;
      } else {
        setErrorText(null);
        return true;
      }
    }
  }

  void setErrorText(errorText) {
    setState(() {
      _errorText = errorText;
    });
  }
}
